### ISSUE TITLE
请问我该如何访问你图中那个控制页面

### ISSUE THREAD

**Issue by fanpiao** [gogo-easy/ngr#19]
请问我该如何访问你图中那个控制页面

**Comment by fanpiao** [comment]
2019/12/06 14:26:49 [error] 308#308: *8645 [lua] router_initializer.lua:238: [business-error]-api_groups init is empty, context: ngx.timer
2019/12/06 14:26:49 [error] 308#308: *8645 [lua] main.lua:161: [system-error]-[Load core configuration] worker[1] load API Group,targets,AB divides to local cache failed, context: ngx.timer
还有这个错误

**Comment by Fijileijun** [comment]
> 请问我该如何访问你图中那个控制页面

预计会在v1.0.3 版本全面开放

**Comment by Fijileijun** [comment]
> 2019/12/06 14:26:49 [error] 308#308: *8645 [lua] router_initializer.lua:238: [business-error]-api_groups init is empty, context: ngx.timer
> 2019/12/06 14:26:49 [error] 308#308: *8645 [lua] main.lua:161: [system-error]-[Load core configuration] worker[1] load API Group,targets,AB divides to local cache failed, context: ngx.timer
> 还有这个错误

请说明下该error 出现的场景，非常感谢

**Comment by wuyachun91** [comment]
> > 2019/12/06 14:26:49 [error] 308#308: *8645 [lua] router_initializer.lua:238: [business-error]-api_groups init is empty, context: ngx.timer
> > 2019/12/06 14:26:49 [error] 308#308: *8645 [lua] main.lua:161: [system-error]-[Load core configuration] worker[1] load API Group,targets,AB divides to local cache failed, context: ngx.timer
> > 还有这个错误
> 
> 请说明下该error 出现的场景，非常感谢
我ngr、ngrAdmin启动后，ngr的gateway.local.error.log日志报错也是这样

**Comment by fanpiao** [comment]
有段时间前的事情了，我忘记了，不好意思






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wuyachun"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 晚上10:41
收件人:&nbsp;"gogo-easy/ngr"<ngr@noreply.github.com&gt;;
抄送:&nbsp;"℡つ流年oО "<651260546@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gogo-easy/ngr] 请问我该如何访问你图中那个控制页面 (#19)



  
2019/12/06 14:26:49 [error] 308#308: *8645 [lua] router_initializer.lua:238: [business-error]-api_groups init is empty, context: ngx.timer
 2019/12/06 14:26:49 [error] 308#308: *8645 [lua] main.lua:161: [system-error]-[Load core configuration] worker[1] load API Group,targets,AB divides to local cache failed, context: ngx.timer
 还有这个错误
  
请说明下该error 出现的场景，非常感谢
 我ngr、ngrAdmin启动后，ngr的gateway.local.error.log日志报错也是这样

**Comment by fanpiao** [comment]
我刚试了下就是正常开启ngr start 启动也没报异常，但是去看/var/log/ngr/gateway.local.error.log  一只不停的打印这个错误

**Comment by wuyachun91** [comment]
@fanpiao  你好，我启动成功后，如何登陆ngr的管理界面，谢谢了

**Comment by wuyachun91** [comment]
我启动后，在浏览器输入ip，结果走的是default_server，并没有走到gateway.local，感觉还是和gateway.local.error.log网关报错有关

**Comment by wuyachun91** [comment]
> 我刚试了下就是正常开启ngr start 启动也没报异常，但是去看/var/log/ngr/gateway.local.error.log 一只不停的打印这个错误
我启动后，在浏览器输入ip，结果走的是default_server，并没有走到gateway.local，感觉还是和gateway.local.error.log网关报错有关

**Comment by Fijileijun** [comment]
> @fanpiao 你好，我启动成功后，如何登陆ngr的管理界面，谢谢了

看下ngrAdminPortal项目：https://github.com/gogo-easy/ngrAdminPortal
