### ISSUE TITLE
关于API的默认账号密码

### ISSUE THREAD

**Issue by PockyRayzz** [gogo-easy/ngr#36]
#### 使用版本 Using version

v1.0.3

#### 需求或问题的场景 requirement & issue's  scene

ngrAdmin登陆后调用的服务端7777端口的API，但是需要basic验证，这个验证的账号密码默认是什么？

#### 截图 screenshot
![QQ图片20200204133352](https://user-images.githubusercontent.com/29441283/73716820-09c53c00-4753-11ea-8da8-817c9b1f417d.png)

**Comment by Fijileijun** [comment]
username: admin
password: ngr_admin
